
### 1. (C)REATE new laptop type 
POST http://localhost:3000/addlaptoptype.test.php
Content-Type: application/x-www-form-urlencoded

laptopTypeID=4
&laptopTypeCode=GAME
&laptopTypeName=Gaming Laptop
&laptopShelfNumber=6
### 2. (R)EAD or list the laptop types
GET http://localhost:3000/listlaptoptypes.test.php
### 3. (U)PDATE the laptop type 
POST http://localhost:3000/changelaptoptype.test.php
Content-Type: application/x-www-form-urlencoded

laptopTypeID=4
&laptopTypeCode=ASUSGAME
&laptopTypeName=Gaming & Studio Laptop
&laptopShelfNumber=10
### 4. (D)ELETE the laptop type 
POST http://localhost:3000/removelaptoptype.test.php
Content-Type: application/x-www-form-urlencoded

laptopTypeID=4